- hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    phone_number: 0123456789
  tasks:
  - name: Modify particular word in a file
    template:
      src: /home/ec2-user/sample.xml.j2
      dest: /home/ec2-user/sample.xml
  - name: Get file content
    shell: cat /home/ec2-user/sample.xml
    register: file_content
  - name: View file content
    debug:
      var: file_content.stdout_lines