- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Block and Rescue explanation
    block:
    - name: Print task 1 in Block
      debug:
        msg: Task 1
    - name: Print task 2 in Block
      shell: /usr/bin/false
    - name: Print task 3 in Block
      debug:
        msg: Task 3
    rescue:
    - name: Print task 1 in Rescue
      debug:
        msg: Task 1 Rescue
    - name: Print task 2 in Rescue
      debug:
        msg: Task 2 Rescue
    - name: Print task 3 in Rescue
      debug:
        msg: Task 3 Rescue
    always:
    - name: Print task 1 in always
      debug:
        msg: Task 1 always
    - name: Print task 2 in always
      debug:
        msg: Task 2 always
    - name: Print task 3 in always
      debug:
        msg: Task 3 always